services: 
  nginx:
    image: nailz2k/nginx-server
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    links:
        - emails
  emails:
    image: nailz2k/emails
    container_name: emails
    ports:
        - 3003:3003
  client:
    image: nailz2k/client
    container_name: client
    ports:
        - 4200:4200
